services:
  mysql:
    image: mysql:oracle
    container_name: mysql_tfg
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: news_db
    expose:
      - "3306"
    networks:
      - tfg_network
    restart: always

  redis:
    image: redis:8-alpine
    container_name: redis_tfg
    networks:
      - tfg_network
    expose:
      - "6379"
    restart: always

  ollama:
    image: ollama/ollama
    container_name: ollama_tfg
    networks:
      - tfg_network
    expose:
      - "11434"
    restart: always
    volumes:
      ollama-models:/root/.ollama
  
  backend:
    ports:
      - "8080:8080"
    networks:
      - tfg_network
    restart: always

  sentiment_analysis:
    build:
      context: ./backend/Analysis
      dockerfile: Dockerfile

    container_name: analysis_tfg

    enviroment:
      - OLLAMA_HOST=ollama_tfg
      - REDIS_HOST=redis_tfg
      - MYSQL_HOST=mysql_tfg
    networks:
      - tfg_network
    restart: always

  web_scraping:
    build:
      context: ./backend/Scraping
      dockerfile: Dockerfile
    container_name: scraping_tfg

    enviroment:
      - REDIS_HOST=redis_tfg
      - MYSQL_HOST=mysql_tfg
    networks:
      - tfg_network
    restart: always

  model_server:
    build:
      context: ./models_service
      dockerfile: Dockerfile
    
    container_name: models_tfg

    expose:
      - "7777"
    networks:
      - tfg_network
    restart: always


networks:
  tfg_network:
    driver: bridge

volumes:
  ollama_models: